# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.resources\ui_CustomToolbar.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from CustomToolBar.gui import resources_rc
from qgsfilterlineedit import QgsFilterLineEdit


class Ui_CustomToolbarDialog(object):

    def setupUi(self, CustomToolbarDialog):
        CustomToolbarDialog.setObjectName("CustomToolbarDialog")
        CustomToolbarDialog.resize(833, 443)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CustomToolbarDialog.setWindowIcon(icon)
        CustomToolbarDialog.setAccessibleDescription("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(CustomToolbarDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.help_btn = QtWidgets.QPushButton(CustomToolbarDialog)
        self.help_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.help_btn.setStyleSheet("text-align:left;")
        self.help_btn.setFlat(True)
        self.help_btn.setObjectName("help_btn")
        self.horizontalLayout.addWidget(self.help_btn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(CustomToolbarDialog)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/images/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(CustomToolbarDialog)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/images/collapse.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_6.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)
        self.groupBox = QtWidgets.QGroupBox(CustomToolbarDialog)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.searchBox = QgsFilterLineEdit(self.groupBox)
        self.searchBox.setObjectName("searchBox")
        self.verticalLayout_4.addWidget(self.searchBox)
        self.ToolBars = QtWidgets.QTreeWidget(self.groupBox)
        self.ToolBars.setStyleSheet("")
        self.ToolBars.setDragEnabled(True)
        self.ToolBars.setDragDropOverwriteMode(False)
        self.ToolBars.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.ToolBars.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.ToolBars.setAlternatingRowColors(True)
        self.ToolBars.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.ToolBars.setItemsExpandable(True)
        self.ToolBars.setAllColumnsShowFocus(False)
        self.ToolBars.setWordWrap(False)
        self.ToolBars.setObjectName("ToolBars")
        self.ToolBars.header().setVisible(False)
        self.ToolBars.header().setSortIndicatorShown(False)
        self.ToolBars.header().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.ToolBars)
        self.horizontalLayout_4.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.new_btn = QtWidgets.QPushButton(CustomToolbarDialog)
        self.new_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.new_btn.setStyleSheet("border:1px solid #6E6E6E;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"min-width: 3em;\n"
"padding: 2px;\n"
"")
        self.new_btn.setFlat(True)
        self.new_btn.setObjectName("new_btn")
        self.verticalLayout.addWidget(self.new_btn)
        self.rename_btn = QtWidgets.QPushButton(CustomToolbarDialog)
        self.rename_btn.setEnabled(False)
        self.rename_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rename_btn.setStyleSheet("border:1px solid #6E6E6E;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"min-width: 3em;\n"
"padding: 2px;")
        self.rename_btn.setFlat(True)
        self.rename_btn.setObjectName("rename_btn")
        self.verticalLayout.addWidget(self.rename_btn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.delete_btn = QtWidgets.QPushButton(CustomToolbarDialog)
        self.delete_btn.setEnabled(False)
        self.delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn.setStyleSheet("border:1px solid #6E6E6E;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"min-width: 3em;\n"
"padding: 2px;")
        self.delete_btn.setFlat(True)
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout.addWidget(self.delete_btn)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.Save_btn = QtWidgets.QPushButton(CustomToolbarDialog)
        self.Save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Save_btn.setStyleSheet("border:1px solid #6E6E6E;\n"
"border-style: outset;\n"
"border-width: 1px;\n"
"border-radius: 3px;\n"
"padding: 2px;\n"
"")
        self.Save_btn.setFlat(True)
        self.Save_btn.setObjectName("Save_btn")
        self.verticalLayout.addWidget(self.Save_btn)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(CustomToolbarDialog)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.MyToolsBars = QtWidgets.QTreeWidget(self.groupBox_2)
        self.MyToolsBars.setEnabled(False)
        self.MyToolsBars.setStyleSheet("")
        self.MyToolsBars.setDragEnabled(False)
        self.MyToolsBars.setDragDropOverwriteMode(False)
        self.MyToolsBars.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.MyToolsBars.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.MyToolsBars.setAlternatingRowColors(True)
        self.MyToolsBars.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.MyToolsBars.setAutoExpandDelay(-1)
        self.MyToolsBars.setRootIsDecorated(True)
        self.MyToolsBars.setItemsExpandable(True)
        self.MyToolsBars.setObjectName("MyToolsBars")
        self.MyToolsBars.header().setVisible(False)
        self.verticalLayout_3.addWidget(self.MyToolsBars)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.My_expand = QtWidgets.QPushButton(CustomToolbarDialog)
        self.My_expand.setEnabled(False)
        self.My_expand.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.My_expand.setText("")
        self.My_expand.setIcon(icon1)
        self.My_expand.setAutoDefault(False)
        self.My_expand.setFlat(True)
        self.My_expand.setObjectName("My_expand")
        self.verticalLayout_8.addWidget(self.My_expand)
        self.My_Collapse = QtWidgets.QPushButton(CustomToolbarDialog)
        self.My_Collapse.setEnabled(False)
        self.My_Collapse.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.My_Collapse.setText("")
        self.My_Collapse.setIcon(icon2)
        self.My_Collapse.setAutoDefault(False)
        self.My_Collapse.setFlat(True)
        self.My_Collapse.setObjectName("My_Collapse")
        self.verticalLayout_8.addWidget(self.My_Collapse)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)

        self.retranslateUi(CustomToolbarDialog)
        self.ToolBars.itemPressed['QTreeWidgetItem*', 'int'].connect(CustomToolbarDialog.QgisToolsClick)
        self.MyToolsBars.itemClicked['QTreeWidgetItem*', 'int'].connect(CustomToolbarDialog.MyToolsClick)
        self.rename_btn.clicked.connect(CustomToolbarDialog.RenameToolBar)
        self.new_btn.clicked.connect(CustomToolbarDialog.NewToolBar)
        self.delete_btn.clicked.connect(CustomToolbarDialog.DeleteToolBar)
        self.Save_btn.clicked.connect(CustomToolbarDialog.SaveTools)
        self.pushButton.clicked.connect(CustomToolbarDialog.ExpandQgis)
        self.pushButton_2.clicked.connect(CustomToolbarDialog.CollapseQgis)
        self.My_expand.clicked.connect(CustomToolbarDialog.ExpandMyTools)
        self.My_Collapse.clicked.connect(CustomToolbarDialog.CollapseMyTools)
        self.searchBox.textChanged['QString'].connect(CustomToolbarDialog.Search)
        self.help_btn.clicked.connect(CustomToolbarDialog.about)
        QtCore.QMetaObject.connectSlotsByName(CustomToolbarDialog)

    def retranslateUi(self, CustomToolbarDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomToolbarDialog.setWindowTitle(_translate("CustomToolbarDialog", "Create customs ToolBars"))
        self.help_btn.setText(_translate("CustomToolbarDialog", "About"))
        self.pushButton.setToolTip(_translate("CustomToolbarDialog", "Expand all"))
        self.pushButton_2.setToolTip(_translate("CustomToolbarDialog", "Collapse all"))
        self.groupBox.setTitle(_translate("CustomToolbarDialog", "Qgis Tools"))
        self.searchBox.setToolTip(_translate("CustomToolbarDialog", "Enter algorithm name to filter list"))
        self.searchBox.setPlaceholderText(_translate("CustomToolbarDialog", "Search..."))
        self.ToolBars.setSortingEnabled(False)
        self.new_btn.setText(_translate("CustomToolbarDialog", "New ToolBar"))
        self.rename_btn.setText(_translate("CustomToolbarDialog", "Rename ToolBar"))
        self.delete_btn.setText(_translate("CustomToolbarDialog", "Delete ToolBar or Tool"))
        self.Save_btn.setText(_translate("CustomToolbarDialog", "Save Changes"))
        self.groupBox_2.setTitle(_translate("CustomToolbarDialog", "My ToolBars"))
        self.My_expand.setToolTip(_translate("CustomToolbarDialog", "Expand all"))
        self.My_Collapse.setToolTip(_translate("CustomToolbarDialog", "Collapse all"))

